### PR TITLE
Added finally block to handle consumeQueue

### LINKED ISSUE #13: consumeQueue on Error
What is the best way to forward the Operation to the next link in case of any error. This might be necessary if I need the original graphql request promise be rejected in case there is an error in refreshing the token.

### PR DESCRIPTION
**Pull request by masesisaac**
This fixes #13

### CODE REVIEW

**Comment by zuqini** [comment]
I encountered the same issue. Since apollo-link-token-refresh is meant to be a non-terminating link, my opinion is that the operation should always be forwarded regardless of if there's errors - 
```
.then(this.handleFetch)
.catch(this.handleError)
.finally(() => {
    this.fetching = false;
    this.queue.consumeQueue();
});
```

**Comment by masesisaac** [comment]
Oh yeah, I think this is a better opinion. Let me change the PR to reflect that.

**Comment by newsiberian** [comment]
Hi, @masesisaac , thanks for the PR. Please, let me know when it will be ready

**Comment by masesisaac** [comment]
Hi @newsiberian, Thanks for the feedback, I think the PR is reay now.

**Pull request merged**
